inode/directory=nemo.desktop
application/x-gnome-saved-search=nemo.desktop
x-directory/normal=nemo.desktop
x-directory/gnome-default-handler=nemo.desktop
application/zip=nemo-extract-to-folder.desktop
application/x-7z-compressed=nemo-extract-to-folder.desktop
application/x-rar=nemo-extract-to-folder.desktop
application/x-rar-compressed=nemo-extract-to-folder.desktop
application/x-tar=nemo-extract-to-folder.desktop
application/x-gzip=nemo-extract-to-folder.desktop
application/gzip=nemo-extract-to-folder.desktop
application/x-bzip2=nemo-extract-to-folder.desktop
application/x-xz=nemo-extract-to-folder.desktop
application/x-compressed-tar=nemo-extract-to-folder.desktop
